# Generated by Django 5.2.7 on 2025-10-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='showroom',
            fields=[
                ('Car_model', models.CharField(max_length=20)),
                ('Series', models.CharField()),
                ('Color', models.CharField(max_length=15)),
                ('Engine_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Fancy_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
